AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "vendor/**/*"
    - "packaging/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
